[tool.black]
target-version = ["py37"]

[tool.setuptools_scm]
write_to = "Lib/glyphspkg/_version.py"

[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"
